# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_cadastro_livro.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(926, 547)
        MainWindow.setWindowOpacity(1.0)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(290, 152, 291, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.titulo = QtWidgets.QLineEdit(self.centralwidget)
        self.titulo.setGeometry(QtCore.QRect(290, 183, 291, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.titulo.setFont(font)
        self.titulo.setObjectName("titulo")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(350, 20, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.botao_salvar_livro = QtWidgets.QPushButton(self.centralwidget)
        self.botao_salvar_livro.setGeometry(QtCore.QRect(740, 340, 93, 28))
        self.botao_salvar_livro.setObjectName("botao_salvar_livro")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(290, 218, 291, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.autor = QtWidgets.QLineEdit(self.centralwidget)
        self.autor.setGeometry(QtCore.QRect(290, 249, 291, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.autor.setFont(font)
        self.autor.setObjectName("autor")
        self.qtd_pag = QtWidgets.QLineEdit(self.centralwidget)
        self.qtd_pag.setGeometry(QtCore.QRect(615, 182, 191, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.qtd_pag.setFont(font)
        self.qtd_pag.setObjectName("qtd_pag")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(615, 217, 169, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.ano_publi = QtWidgets.QLineEdit(self.centralwidget)
        self.ano_publi.setGeometry(QtCore.QRect(615, 248, 188, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ano_publi.setFont(font)
        self.ano_publi.setObjectName("ano_publi")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(120, 140, 141, 192))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.botao_selecionar_img = QtWidgets.QPushButton(self.centralwidget)
        self.botao_selecionar_img.setGeometry(QtCore.QRect(120, 340, 141, 28))
        self.botao_selecionar_img.setObjectName("botao_selecionar_img")
        self.colocar_imagem = QtWidgets.QLabel(self.centralwidget)
        self.colocar_imagem.setGeometry(QtCore.QRect(120, 140, 141, 191))
        self.colocar_imagem.setText("")
        self.colocar_imagem.setObjectName("colocar_imagem")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(30, 80, 861, 351))
        self.textBrowser.setObjectName("textBrowser")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(610, 150, 221, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.textBrowser.raise_()
        self.label.raise_()
        self.titulo.raise_()
        self.label_2.raise_()
        self.botao_salvar_livro.raise_()
        self.label_3.raise_()
        self.autor.raise_()
        self.qtd_pag.raise_()
        self.label_5.raise_()
        self.ano_publi.raise_()
        self.textBrowser_2.raise_()
        self.botao_selecionar_img.raise_()
        self.colocar_imagem.raise_()
        self.label_7.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 926, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionMOSTRAR_LIVROS_CADASTRADOS = QtWidgets.QAction(MainWindow)
        self.actionMOSTRAR_LIVROS_CADASTRADOS.setObjectName("actionMOSTRAR_LIVROS_CADASTRADOS")
        self.actionBUSCAR = QtWidgets.QAction(MainWindow)
        self.actionBUSCAR.setObjectName("actionBUSCAR")
        self.actionEDITAR = QtWidgets.QAction(MainWindow)
        self.actionEDITAR.setObjectName("actionEDITAR")
        self.actionLISTAR = QtWidgets.QAction(MainWindow)
        self.actionLISTAR.setObjectName("actionLISTAR")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Título:"))
        self.label_2.setText(_translate("MainWindow", "Dados do livro"))
        self.botao_salvar_livro.setText(_translate("MainWindow", "SALVAR"))
        self.label_3.setText(_translate("MainWindow", "Autor: "))
        self.label_5.setText(_translate("MainWindow", "Ano de publicação:"))
        self.botao_selecionar_img.setText(_translate("MainWindow", "SELECIONAR IMAGEM"))
        self.label_7.setText(_translate("MainWindow", "Quantidade de páginas:"))
        self.actionMOSTRAR_LIVROS_CADASTRADOS.setText(_translate("MainWindow", "MOSTRAR LIVROS CADASTRADOS"))
        self.actionBUSCAR.setText(_translate("MainWindow", "BUSCAR"))
        self.actionEDITAR.setText(_translate("MainWindow", "EDITAR"))
        self.actionLISTAR.setText(_translate("MainWindow", "LISTAR LIVROS CADASTRADOS"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
